# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MATILDA
author: Phillip Schuster
copyright: "2026"
logo: images/MATILDA_Logo_processes.png

execute:
  execute_notebooks: off

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/phiscu/matilda_edu
  branch: no_outputs

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab"

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options:
      icon_links:
        - name: GitHub
          url: https://github.com/phiscu/matilda_edu
          icon: "fa-brands fa-github"
          type: fontawesome
        - name: Launch MATILDA in Binder
          url: https://mybinder.org/v2/gh/phiscu/matilda_edu/no_outputs?urlpath=lab/tree/matilda_binder_landing_page.md
          icon: "fa-solid fa-rocket"
          type: fontawesome
